name: syncmyschedule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  flutter_vector_icons: ^2.0.0
  provider: ^6.1.5
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.0
  cloud_functions: ^6.0.0
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  device_calendar: ^4.3.3
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  timezone: ^0.9.4
  share_plus: ^11.1.0
  permission_handler: ^12.0.1
  file_picker: ^10.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"