// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYbUD_7QFRdQhGMoaPOitW57OyB8HoPZo',
    appId: '1:237228165143:web:20c4b404a1b9c6557eb452',
    messagingSenderId: '237228165143',
    projectId: 'syncmyschedule-58722',
    authDomain: 'syncmyschedule-58722.firebaseapp.com',
    storageBucket: 'syncmyschedule-58722.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWOZyM3lwqd_oYkaS3nLjiLsM3xOLYrE',
    appId: '1:237228165143:android:3e9767106ab916a97eb452',
    messagingSenderId: '237228165143',
    projectId: 'syncmyschedule-58722',
    storageBucket: 'syncmyschedule-58722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_8U4rRAtWTuoGbglR4dyrEkjZd3ajlw',
    appId: '1:237228165143:ios:80700b5accd2cc877eb452',
    messagingSenderId: '237228165143',
    projectId: 'syncmyschedule-58722',
    storageBucket: 'syncmyschedule-58722.firebasestorage.app',
    iosBundleId: 'com.syncmyschedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_8U4rRAtWTuoGbglR4dyrEkjZd3ajlw',
    appId: '1:237228165143:ios:5213dcf04118c9257eb452',
    messagingSenderId: '237228165143',
    projectId: 'syncmyschedule-58722',
    storageBucket: 'syncmyschedule-58722.firebasestorage.app',
    iosBundleId: 'com.example.syncmyschedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYbUD_7QFRdQhGMoaPOitW57OyB8HoPZo',
    appId: '1:237228165143:web:c81976541b66cff67eb452',
    messagingSenderId: '237228165143',
    projectId: 'syncmyschedule-58722',
    authDomain: 'syncmyschedule-58722.firebaseapp.com',
    storageBucket: 'syncmyschedule-58722.firebasestorage.app',
  );
}
